### ISSUE TITLE
Script now working currently

### ISSUE THREAD

**Issue by grossgrundbesitzer** [ugurkocde/AutoPilot_Import_GUI#3]
Hi Ugur,
The script does not work since the change to Graph 2.0. Microsoft is always very slow to incorporate the changes in their script. Would it be possible that you give the option that also with your gui the community script of Andrews Taylor is called?
Thank you! 
Best regards

**Comment by ugurkocde** [comment]
Hi [grossgrundbesitzer](https://github.com/grossgrundbesitzer), 

this tool uses the GUI of Michael Niehaus. He already updated it and I have verified it multiple times with this GUI.

It works as of today and no change is necessary from my point of view.

Best regards
Ugur
